### ISSUE TITLE
Inner traces

### ISSUE THREAD

**Issue by Immortalin** [Jan--Henrik/electrostatic-adhesion-plate#2]
Is it possible to use a multilayer board design with only inner traces and skip the Kapton/PlastiDip step entirely?

**Comment by Jana-Marie** [comment]
Probably, I recently ordered such a design. It should be delivered in a few days. I can tell you more then :)

**Comment by lalalandrus** [comment]
dave @ eeevblog did a video on a commercial whiteboard. it seems they used a wave pattern to promote interaction with the + and - regions. perhaps a suggestion is to meander the traces for the + and the - to improve the adhesion but not so close that it gets nullified.

**Comment by Jana-Marie** [comment]
@lalalandrus I've looked into that topic, there are several papers out there exploring electrostatic adhesion for grippers. Most papers suggested that a electrode pattern like I use it generates the highest adhesion force. However, this pattern is hard to produce, if you have to glue it, such a meander pattern is much easier to apply.

**Comment by Gray-Stone** [comment]
I wonder if the trace width and spacing makes any difference, and what ratio would be best?

**Comment by Jana-Marie** [comment]
Hey @Gray-Stone, sorry for the late reply. Indeed it does, a ration of 2:1 (Trace 2 : width 1) seems to be a good start. As for the actual width, 1-3mm space to 3-9mm trace seems to work good. (All informations obtained from papers, I haven't found the best ratio/size by myself yet) :)

**Comment by Immortalin** [comment]
@Jan--Henrik so how did the inner traces ones fare?

**Comment by Immortalin** [comment]
Also is it possible to round out the corners a bit more just in case of corona?

**Comment by Immortalin** [comment]
Also, for covering over the solders at the back, are you just using Kapton tape?

**Comment by Jana-Marie** [comment]
> @Jan--Henrik so how did the inner traces ones fare?

Hey, I've ordered and tested serveral different 4-layer PCBs. There is a adhesion force but it is much weaker then with direct copper on a 2-layer board. :/

> Also is it possible to round out the corners a bit more just in case of corona?

This project is a OSHW project, so you can do that yourself if you want :) However I haven't noticed any corona yet, so it is probably not needed.

> Also, for covering over the solders at the back, are you just using Kapton tape?

Yep, it is quite complicated to apply, using water+soap to prevent air bubbles worked very well. Make sure to bake everything afterwards (~60°C ~2h) to remove any moisture. PlastiDip (spray-able rubber) also worked, but has a weaker dielectric strength.

**Comment by Immortalin** [comment]
I am considering making an even lower budget version with copper tape and paper and lamination.

**Comment by Gray-Stone** [comment]
> I am considering making an even lower budget version with copper tape and paper and lamination.

I've tryied this. Copper tape on a hardboard (which is dense cardboard), sucks up at least a paper with just 8 stripes of 1inch wide copper tape. (about 1Kv)
