### ISSUE TITLE
Castellation/Jigsaw

### ISSUE THREAD

**Issue by Immortalin** [Jan--Henrik/electrostatic-adhesion-plate#3]
Join together like lego

**Comment by Immortalin** [comment]
Like this: https://electronics.stackexchange.com/questions/35625/soldering-pcbs-directly-together

**Comment by Jana-Marie** [comment]
https://github.com/Jan--Henrik/electrostatic-adhesion-plate/raw/master/Images/f03ba77f-4d8d-44b8-966d-36029fc7bf42.jpeg
You can do that already with the current PCB, but a SMD lego connector sounds very nice :D

**Comment by Immortalin** [comment]
Won't a castellate wavy edges offer better grip than a perfectly smooth one?

**Comment by Jana-Marie** [comment]
It will, but it also will expose the high voltage to the front of the PCB, I want to avoid that.
