### ISSUE TITLE
Video demo links broken

### ISSUE THREAD

**Issue by pzl** [Jan--Henrik/electrostatic-adhesion-plate#5]
Came across this project and was interested to see it in action!

However the demo video links in the readme are twitter links that appear to no longer work. 

Do you still have the demo clips? Can they be reuploaded somewhere else?

**Comment by Jana-Marie** [comment]
Sure, here!

https://github.com/user-attachments/assets/e9a8f286-f70a-4371-af7a-df20809293cf


https://github.com/user-attachments/assets/fc1b60f5-51d2-4803-b8a3-286581b4381b

**Comment by pzl** [comment]
Thank you!!

this helped put an intuitive feel into how much grab there was, though I know you documented the numbers here.
